spring:
  application:
    name: ${APP_NAME}
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jackson:
    mapper:
      sort-properties-alphabetically: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${SPRING_DATASOURCE_DIALECT}
server:
    port: ${PORT}

management:
  endpoints:
    access:
      default: none
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      access: read-only
      probes:
        enabled: true
      #show-details: always #for debugging, alternative "always/when-authorized"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true